<?php

return [
    'Single' => [
        'names' => [
            "Budget Single Room",
            "Deluxe Single Room",
            "Deluxe Single Room with Balcony",
            "Deluxe Single Room with Sea View",
            "Economy Single Room",
            "Large Single Room",
            "New Year's Eve Special - Single Room",
            "Single Room",
            "Single Room - Disability Access",
            "Single Room with Balcony",
            "Single Room with Bath",
            "Single Room with Bathroom",
            "Single Room with Garden View",
            "Single Room with Lake View",
            "Single Room with Mountain View",
            "Single Room with Park View",
            "Single Room with Pool View",
            "Single Room with Private Bathroom",
            "Single Room with Private External Bathroom",
            "Single Room with Sea View",
            "Single Room with Shared Bathroom",
            "Single Room with Shared Shower and Toilet",
            "Single Room with Shared Toilet",
            "Single Room with Shower",
            "Single Room with Terrace",
            "Small Single Room",
            "Standard Single Room",
            "Standard Single Room with Mountain View",
            "Standard Single Room with Sauna",
            "Standard Single Room with Sea View",
            "Standard Single Room with Shared Bathroom",
            "Standard Single Room with Shower",
            "Superior Single Room",
            "Superior Single Room with Lake View",
            "Superior Single Room with Sea View",
        ],
    ],
    'Double' => [
        'names' => [
            "Budget Double Room",
            "Business Double Room with Gym Access",
            "Deluxe Double Room",
            "Deluxe Double Room (1 adult + 1 child",
            "Deluxe Double Room (1 adult + 2 children",
            "Deluxe Double Room (2 Adults + 1 Child",
            "Deluxe Double Room with Balcony",
            "Deluxe Double Room with Balcony and Sea View",
            "Deluxe Double Room with Bath",
            "Deluxe Double Room with Castle View",
            "Deluxe Double Room with Extra Bed",
            "Deluxe Double Room with Sea View",
            "Deluxe Double Room with Shower",
            "Deluxe Double Room with Side Sea View",
            "Deluxe Double or Twin Room",
            "Deluxe King Room",
            "Deluxe Queen Room",
            "Deluxe Room",
            "Deluxe Room (1 adult + 1 child",
            "Deluxe Room (1 adult + 2 children",
            "Deluxe Room (2 Adults + 1 Child",
            "Double Room",
            "Double Room (1 Adult + 1 Child",
            "Double Room - Disability Access",
            "Double Room with Balcony",
            "Double Room with Balcony (2 Adults + 1 Child",
            "Double Room with Balcony (3 Adults",
            "Double Room with Balcony and Sea View",
            "Double Room with Extra Bed",
            "Double Room with Garden View",
            "Double Room with Lake View",
            "Double Room with Mountain View",
            "Double Room with Patio",
            "Double Room with Pool View",
            "Double Room with Private Bathroom",
            "Double Room with Private External Bathroom",
            "Double Room with Sea View",
            "Double Room with Shared Bathroom",
            "Double Room with Shared Toilet",
            "Double Room with Spa Bath",
            "Double Room with Terrace",
            "Economy Double Room",
            "King Room",
            "King Room - Disability Access",
            "King Room with Balcony",
            "King Room with Garden View",
            "King Room with Lake View",
            "King Room with Mountain View",
            "King Room with Pool View",
            "King Room with Roll-In Shower - Disability Access",
            "King Room with Sea View",
            "King Room with Spa Bath",
            "Large Double Room",
            "Queen Room",
            "Queen Room - Disability Access",
            "Queen Room with Balcony",
            "Queen Room with Garden View",
            "Queen Room with Pool View",
            "Queen Room with Sea View",
            "Queen Room with Shared Bathroom",
            "Queen Room with Spa Bath",
            "Small Double Room",
            "Standard Double Room",
            "Standard Double Room with Fan",
            "Standard Double Room with Shared Bathroom",
            "Standard King Room",
            "Standard Queen Room",
            "Superior Double Room",
            "Superior King Room",
            "Superior Queen Room",
        ],
    ],
    'Twin' => [
        'names' => [
            "Budget Twin Room",
            "Deluxe Double Room with Two Double Beds",
            "Deluxe Queen Room with Two Queen Beds",
            "Deluxe Twin Room",
            "Deluxe Twin Room with Sea View",
            "Double Room with Two Double Beds",
            "Economy Twin Room",
            "King Room with Two King Beds",
            "Large Twin Room",
            "Queen Room with Two Queen Beds",
            "Queen Room with Two Queen Beds - Disability Access",
            "Small Twin Room",
            "Standard Double Room with Two Double Beds",
            "Standard Queen Room with Two Queen Beds",
            "Standard Twin Room",
            "Standard Twin Room with Garden View",
            "Standard Twin Room with Mountain View",
            "Standard Twin Room with Sea View",
            "Standard Twin Room with Shared Bathroom",
            "Standard Twin Room with Sofa",
            "Superior Double Room with Two Double Beds",
            "Superior King or Twin Room",
            "Superior Queen Room with Two Queen Beds",
            "Superior Twin Room",
            "Superior Twin Room with City View",
            "Superior Twin Room with Garden View",
            "Superior Twin Room with Sauna",
            "Superior Twin Room with Sea View",
            "Twin Room",
            "Twin Room - Disability Access",
            "Twin Room with Balcony",
            "Twin Room with Bath",
            "Twin Room with Bathroom",
            "Twin Room with City View",
            "Twin Room with Extra Bed",
            "Twin Room with Garden View",
            "Twin Room with Lake View",
            "Twin Room with Mountain View",
            "Twin Room with Pool View",
            "Twin Room with Private Bathroom",
            "Twin Room with Private External Bathroom",
            "Twin Room with Sea View",
            "Twin Room with Shared Bathroom",
            "Twin Room with Shared Toilet",
            "Twin Room with Shower",
            "Twin Room with Terrace",
            "Twin Room with View",
        ],
    ],
    'Twin/Double' => [
        'names' => [
            "Budget Double or Twin Room",
            "Cabin on Boat",
            "Deluxe Double or Twin Room",
            "Deluxe Double or Twin Room with Balcony",
            "Deluxe Double or Twin Room with City View",
            "Deluxe Double or Twin Room with Garden View",
            "Deluxe Double or Twin Room with Lake View",
            "Deluxe Double or Twin Room with Mountain View",
            "Deluxe Double or Twin Room with Ocean View",
            "Deluxe Double or Twin Room with Pool Access",
            "Deluxe Double or Twin Room with Pool View",
            "Deluxe Double or Twin Room with River View",
            "Deluxe Double or Twin Room with Sea View",
            "Deluxe Double or Twin Room with Spa Bath",
            "Double or Twin Room",
            "Double or Twin Room - Disability Access",
            "Double or Twin Room with Balcony",
            "Double or Twin Room with Bathroom",
            "Double or Twin Room with Canal View",
            "Double or Twin Room with City View",
            "Double or Twin Room with Extra Bed",
            "Double or Twin Room with Garden View",
            "Double or Twin Room with Harbor View",
            "Double or Twin Room with Lake View",
            "Double or Twin Room with Mountain View",
            "Double or Twin Room with Partial Sea View",
            "Double or Twin Room with Pool View",
            "Double or Twin Room with Private Bathroom",
            "Double or Twin Room with Private External Bathroom",
            "Double or Twin Room with Sea View",
            "Double or Twin Room with Shared Bathroom",
            "Double or Twin Room with Shower",
            "Double or Twin Room with Side Sea View",
            "Double or Twin Room with Spa Access",
            "Double or Twin Room with Swimming Pool Access",
            "Double or Twin Room with Terrace",
            "Double or Twin Room with View",
            "Economy Double or Twin Room",
            "Large Double or Twin Room",
            "Small Double or Twin Room",
            "Standard Cabin on Boat",
            "Standard Double or Twin Room",
            "Standard Double or Twin Room with Balcony",
            "Standard Double or Twin Room with Garden View",
            "Standard Double or Twin Room with Sea View",
            "Superior Cabin on Boat",
            "Superior Deluxe Double or Twin Room ",
            "Superior Double or Twin Room",
            "Superior Double or Twin Room with City View",
            "Superior Double or Twin Room with Garden View",
            "Superior Double or Twin Room with Lake View",
            "Superior Double or Twin Room with Mountain View",
            "Superior Double or Twin Room with Pool View",
            "Superior Double or Twin Room with Sea View",
            "Superior Double or Twin Room with Terrace",
        ],
    ],
    'Triple' => [
        'names' => [
            "Basic Triple Room",
            "Basic Triple Room with Shared Bathroom",
            "Budget Triple Room",
            "Classic Triple Room",
            "Comfort Triple Room",
            "Comfort Triple Room with Shower",
            "Deluxe Triple Room",
            "Deluxe Triple Room with Sea View",
            "Economy Triple Room",
            "Economy Triple Room with Shared Bathroom",
            "Executive Triple Room",
            "Luxury Triple Room",
            "Standard Triple Room",
            "Standard Triple Room with Sea View",
            "Superior Triple Room",
            "Superior Triple Room with Sea View",
            "Triple Room",
            "Triple Room - Disability Access",
            "Triple Room with Balcony",
            "Triple Room with Bath",
            "Triple Room with Bathroom",
            "Triple Room with City View",
            "Triple Room with Garden View",
            "Triple Room with Lake View",
            "Triple Room with Mountain View",
            "Triple Room with Pool View",
            "Triple Room with Private Bathroom",
            "Triple Room with Private External Bathroom",
            "Triple Room with Sea View",
            "Triple Room with Shared Bathroom",
            "Triple Room with Shared Toilet",
            "Triple Room with Shower",
            "Triple Room with Terrace",
            "Triple Room with View",
        ],
    ],
    'Quad' => [
        'names' => [
            "Classic Quadruple Room",
            "Comfort Quadruple Room",
            "Deluxe Quadruple Room",
            "Deluxe Queen Room with Two Queen Beds",
            "Duplex Quadruple Room",
            "Economy Quadruple Room",
            "Economy Quadruple Room with Shared Bathroom",
            "Executive Queen Room with Two Queen Beds",
            "Japanese-Style Quadruple Room",
            "King Room with Two King Beds",
            "Luxury Quadruple Room",
            "Premium Quadruple Room",
            "Quadruple Room",
            "Quadruple Room - Disability Access",
            "Quadruple Room with Balcony",
            "Quadruple Room with Bath",
            "Quadruple Room with Bathroom",
            "Quadruple Room with Garden View",
            "Quadruple Room with Lake View",
            "Quadruple Room with Mountain View",
            "Quadruple Room with Private Bathroom",
            "Quadruple Room with Private External Bathroom",
            "Quadruple Room with Sea View",
            "Quadruple Room with Shared Bathroom",
            "Quadruple Room with Shower",
            "Quadruple Room with Terrace",
            "Queen Room with Two Queen Beds",
            "Queen Room with Two Queen Beds - Disability Access",
            "Standard Quadruple Room",
            "Standard Queen Room with Two Queen Beds",
            "Superior Quadruple Room",
            "Superior Queen Room with Two Queen Beds",
        ],
    ],
    'Family' => [
        'names' => [
            "Deluxe Family Room",
            "Deluxe Family Suite",
            "Family Bungalow",
            "Family Cabin on Boat",
            "Family Double Room",
            "Family Junior Suite",
            "Family Room",
            "Family Room - Disability Access",
            "Family Room with Balcony",
            "Family Room with Bath",
            "Family Room with Bathroom",
            "Family Room with Garden View",
            "Family Room with Lake View",
            "Family Room with Mountain View",
            "Family Room with Private Bathroom",
            "Family Room with Sauna",
            "Family Room with Sea View",
            "Family Room with Shared Bathroom",
            "Family Room with Shower",
            "Family Room with Side Sea View",
            "Family Room with Terrace",
            "Family Studio",
            "Family Suite",
            "Family Suite with Balcony",
            "Japanese-Style Room",
            "Standard Family Room",
            "Superior Family Room",
        ],
    ],
    'Studio' => [
        'names' => [
            "Deluxe Double Studio",
            "Deluxe King Studio",
            "Deluxe Queen Studio ",
            "Deluxe Studio",
            "Duplex Studio",
            "Family Studio",
            "King Studio",
            "King Studio with Sofa Bed",
            "Queen Studio",
            "Queen Studio - Disability Access",
            "Standard Studio",
            "Standard Triple Studio",
            "Studio",
            "Studio - Disability Access",
            "Studio - Split Level",
            "Studio with Balcony",
            "Studio with Garden View",
            "Studio with Lake View",
            "Studio with Mountain View",
            "Studio with Ocean View",
            "Studio with Pool View",
            "Studio with Sea View",
            "Studio with Sofa Bed",
            "Studio with Spa Bath",
            "Studio with Terrace",
            "Superior Studio",
        ],
    ],
    'Dorm Room' => [
        'names' => [
            "10-Bed Female Dormitory Room",
            "10-Bed Male Dormitory Room",
            "10-Bed Mixed Dormitory Room",
            "4-Bed Female Dormitory Room",
            "4-Bed Male Dormitory Room ",
            "4-Bed Mixed Dormitory Room",
            "6-Bed Female Dormitory Room",
            "6-Bed Male Dormitory Room",
            "6-Bed Mixed Dormitory Room",
            "8-Bed Female Dormitory Room",
            "8-Bed Male Dormitory Room",
            "8-Bed Mixed Dormitory Room",
            "Female Dormitory Room",
            "Male Dormitory Room",
            "Mixed Dormitory Room",
        ],
    ],
];
